### PR TITLE
Update reflectometers.md

### PR DESCRIPTION
**Pull request by AntonLeBrun**
Updated to add publication for reflectometer MR at CSNS China https://www.tandfonline.com/doi/abs/10.1080/10448632.2018.1514196?journalCode=gnnw20

### CODE REVIEW

**Comment by arm61** [comment]
Why did you remove the AMOR link too?

**Comment by tomarnoldess** [comment]
That may have been an error... but AMOR link is there now so must have been corrected subsequently

**Comment by arm61** [comment]
😎

**Comment by AntonLeBrun** [comment]
Hi Andrew,

I don't think removing the AMOR link was intentional. I see there is another e-mail from Tom saying it's now back in.

Please could I also have editing writes. My GitHub user name is AntonLeBrun.

Many thanks,
Anton.
OFFICIAL

**Comment by arm61** [comment]
Figured that was the case, was just wanting to make people aware incase it was overlooked. I will add you now.

**Pull request merged**
